# /infra/cloudrun.yaml
# Aligns with PROJECT_BIBLE.md: Section 4, 7
# - Defines the service for declarative deployment to GCP Cloud Run.
# - Injects secrets from GCP Secret Manager, AVOIDING .env files in production.

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: mev-og-nextgen # The name of your Cloud Run service
  annotations:
    run.googleapis.com/launch-stage: BETA
spec:
  template:
    metadata:
      annotations:
        # Run service continuously, not just on requests. CRITICAL for a bot.
        run.googleapis.com/execution-environment: gen2
        autoscaling.knative.dev/minScale: '1' # Keep at least one instance running
        autoscaling.knative.dev/maxScale: '1' # Scale to only 1 for now
    spec:
      containers:
        - image: us-central1-docker.pkg.dev/your-gcp-project-id/mev-repo/mev-og-nextgen:latest # <-- REPLACE with your image path
          ports:
            # We don't need to expose ports for this bot, but health checks could use one.
            # - containerPort: 8080
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
          env:
            - name: LOG_LEVEL
              value: "INFO"
              
            # --- GCP Secret Manager Integration ---
            # This section demonstrates how to securely mount secrets as environment variables.
            # Before deploying, you must create these secrets in GCP Secret Manager.
            - name: EXECUTOR_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: EXECUTOR_PRIVATE_KEY # The name of the secret in GCP
                  key: '1' # The version of the secret (e.g., 'latest' or '1')
            - name: ETH_RPC_URL
              valueFrom:
                secretKeyRef:
                  name: ETH_RPC_URL
                  key: '1'
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: SENTRY_DSN
                  key: '1'
