apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: mev-service
spec:
  template:
    spec:
      containers:
        - image: gcr.io/your-project/mev:latest
          command: ["pytest"]
