# /.github/workflows/ci.yml - FINAL HARDENED version
name: MEV-OG CI/CD Pipeline

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest flake8 mypy
    - name: Run Linter (flake8)
      run: flake8 src/
    - name: Run Type Checker (mypy)
      run: mypy src/
    - name: Run Unit & Integration Tests
      run: pytest

  security-scan:
    runs-on: ubuntu-latest
    needs: lint-and-test
    steps:
      - uses: actions/checkout@v3
      - name: Run Dependency Review for CVEs
        uses: actions/dependency-review-action@v3

  chaos-test-harness:
    runs-on: ubuntu-latest
    needs: security-scan
    steps:
      - uses: actions/checkout@v3
      - name: Build and run chaos environment
        run: docker-compose -f infra/docker-compose.chaos.yml up -d --build
      - name: Wait for services
        run: sleep 20
      - name: Execute chaos tests
        run: docker-compose -f infra/docker-compose.chaos.yml run --rm test-runner
